version: '3.3'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 8098:80
    links:
      - fpm
    volumes:
      - ./:/var/www/ot4et
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
      - ./:/var/www/ot4et
    links:
      - pgsql
  pgsql:
    image: postgres:9.5-alpine
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ot4et
